#!/bin/sh

recurssionCount=0

mvup()
{
  currentDirectory=`pwd`
  for FILE in $currentDirectory/*
  do 
    if [ -d $FILE ]; 
    then
      recurssionCount=`expr $recurssionCount + 1`
      echo "$recurssionCount: Recurssing into directory $FILE."
      cd $FILE
      mvup
      cd ..
      recurssionCount=`expr $recurssionCount - 1`
    elif [ -f $FILE ];
    then
      echo "Moving $FILE up to parent directory."
      mv $FILE ..
    fi
  done;
}

mvupinit()
{
  currentDirectory=`pwd`
  for FILE in $currentDirectory/*
  do 
    if [ -d $FILE ]; 
    then
      recurssionCount=`expr $recurssionCount + 1 `
      echo "$recurssionCount: Recurssing into directory $FILE."
      cd $FILE
      mvup
      cd ..
      recurssionCount=`expr $recurssionCount - 1`
      echo "Removing directory ${FILE:0:${#FILE}-2}."
      rm -R "${FILE:0:${#FILE}-2}" 
    fi
  done;
}

mvupinit
